# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 40b9473054cedfaac4c17826ea11e9884078549c41b41e8d1242d13fe8efd1305754c8b97a006e0e5c427f4c94435c03cc232101943e96215c770015b9adb000

test:
  secret_key_base: ce79b389d80c29e53697208f8036ecde9b1301608da966cd23351e61562c043a394b6b45f47032c5efc36c6dff1dfd5eb5eff6aa3c9b56cd25b6eb68d1089342

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
